// apps/segment-react/src/pages/list/index.tsx
import { useState, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { Table, Tag, Button, Space, Input, Select, Form, Card } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { ArrowLeftOutlined, EyeOutlined, SearchOutlined, ReloadOutlined } from '@ant-design/icons'

interface TaskItem {
  id: number
  name: string
  status: string
  priority: string
}

const listData: TaskItem[] = [
  { id: 1, name: '任务 Alpha', status: '已完成', priority: '高' },
  { id: 2, name: '任务 Beta', status: '进行中', priority: '中' },
  { id: 3, name: '任务 Gamma', status: '待开始', priority: '低' },
  { id: 4, name: '任务 Delta', status: '已完成', priority: '高' },
  { id: 5, name: '任务 Epsilon', status: '进行中', priority: '中' },
]

const statusMap: Record<string, { color: string; label: string }> = {
  '已完成': { color: 'success', label: '已完成' },
  '进行中': { color: 'processing', label: '进行中' },
  '待开始': { color: 'warning', label: '待开始' },
}

const priorityMap: Record<string, string> = {
  '高': 'red',
  '中': 'orange',
  '低': 'green',
}

export default function ListPage() {
  const navigate = useNavigate()
  const [keyword, setKeyword] = useState('')
  const [status, setStatus] = useState<string>()

  const filteredData = useMemo(() =>
    listData.filter((item) => {
      const matchKeyword = !keyword || item.name.includes(keyword)
      const matchStatus = !status || item.status === status
      return matchKeyword && matchStatus
    }),
    [keyword, status],
  )

  const handleReset = () => {
    setKeyword('')
    setStatus(undefined)
  }

  const columns: ColumnsType<TaskItem> = [
    { title: 'ID', dataIndex: 'id', key: 'id', width: 80 },
    { title: '名称', dataIndex: 'name', key: 'name' },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: (s: string) => {
        const statusInfo = statusMap[s]
        return <Tag color={statusInfo?.color}>{statusInfo?.label}</Tag>
      },
    },
    {
      title: '优先级',
      dataIndex: 'priority',
      key: 'priority',
      render: (p: string) => <Tag color={priorityMap[p]}>{p}</Tag>,
    },
    {
      title: '操作',
      key: 'action',
      width: 100,
      render: (_, record) => (
        <Button
          type='link'
          size='small'
          icon={<EyeOutlined />}
          onClick={() => navigate(`/detail?id=${record.id}`)}
        >
          查看
        </Button>
      ),
    },
  ]

  return (
    <div style={{ padding: '28px 32px' }}>
      {/* 搜索表单 */}
      <Card style={{ marginBottom: 16, borderRadius: 8, border: '1px solid #E2E8F0' }}>
        <Form layout='inline'>
          <Form.Item label='关键词'>
            <Input
              placeholder='任务名称'
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              allowClear
              style={{ width: 200 }}
            />
          </Form.Item>
          <Form.Item label='状态'>
            <Select
              placeholder='全部'
              value={status}
              onChange={setStatus}
              allowClear
              style={{ width: 140 }}
              options={[
                { label: '已完成', value: '已完成' },
                { label: '进行中', value: '进行中' },
                { label: '待开始', value: '待开始' },
              ]}
            />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type='primary' icon={<SearchOutlined />}>
                搜索
              </Button>
              <Button icon={<ReloadOutlined />} onClick={handleReset}>
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      {/* 数据表格 */}
      <Card style={{ borderRadius: 8, border: '1px solid #E2E8F0' }}>
        <Space style={{ marginBottom: 16 }}>
          <Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/')}>
            返回
          </Button>
        </Space>

        <Table<TaskItem>
          dataSource={filteredData}
          columns={columns}
          rowKey='id'
          pagination={false}
        />
      </Card>
    </div>
  )
}

// apps/segment-vue2/src/pages/list.vue
<template>
  <div class="page-list">
    <!-- 搜索表单 -->
    <div class="card search-card">
      <el-form :inline="true" :model="searchForm" class="search-form">
        <el-form-item label="关键词">
          <el-input v-model="searchForm.keyword" placeholder="服务名称" clearable />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleSearch">搜索</el-button>
          <el-button @click="handleReset">重置</el-button>
        </el-form-item>
      </el-form>
    </div>

    <!-- 数据表格 -->
    <div class="card">
      <div class="card-title">列表页</div>
      <el-table :data="filteredData" stripe @row-click="viewItem">
        <el-table-column prop="id" label="ID" width="60" />
        <el-table-column prop="name" label="名称" />
        <el-table-column prop="status" label="状态">
          <template slot-scope="{ row }">
            <el-tag :type="row.status === '运行中' ? 'success' : 'warning'" size="small">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createdAt" label="创建时间" />
        <el-table-column label="操作" width="120">
          <template slot-scope="{ row }">
            <el-button size="small" type="primary" @click.stop="viewItem(row)">查看</el-button>
          </template>
        </el-table-column>
      </el-table>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ListPage',
  data() {
    return {
      searchForm: { keyword: '', status: '' },
      listData: [
        { id: 1, name: '服务 A', status: '运行中', createdAt: '2026-06-01 10:00' },
        { id: 2, name: '服务 B', status: '运行中', createdAt: '2026-06-02 14:30' },
        { id: 3, name: '服务 C', status: '已停止', createdAt: '2026-06-03 09:15' },
        { id: 4, name: '服务 D', status: '运行中', createdAt: '2026-06-04 16:45' },
        { id: 5, name: '服务 E', status: '已停止', createdAt: '2026-06-05 11:20' },
      ],
    }
  },
  computed: {
    filteredData() {
      return this.listData.filter((item) => {
        const matchKeyword = !this.searchForm.keyword || item.name.includes(this.searchForm.keyword)
        const matchStatus = !this.searchForm.status || item.status === this.searchForm.status
        return matchKeyword && matchStatus
      })
    },
  },
  methods: {
    handleSearch() { /* 搜索由 computed 自动触发 */ },
    handleReset() {
      this.searchForm.keyword = ''
      this.searchForm.status = ''
    },
    viewItem(item) {
      this.$router.push({ path: '/vue2/detail', query: { id: item.id } })
    },
  },
}
</script>

<style scoped>
.page-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.card {
  background: #fff;
  border: 1px solid #E2E8F0;
  border-radius: 12px;
  padding: 20px;
}
.card-title { font-size: 14px; font-weight: 700; color: #1A202C; margin-bottom: 16px; }
.search-form { margin-bottom: 0; }
.search-card .el-form-item { margin-bottom: 0; }
</style>
