// apps/segment-main/src/pages/404.vue
<template>
  <div class="error-page">
    <el-result icon="warning" title="404" sub-title="页面不存在">
      <template #extra>
        <el-button type="primary" @click="router.push('/')">返回首页</el-button>
      </template>
    </el-result>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
const router = useRouter()
</script>

<style scoped>
.error-page {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
}
</style>

// apps/segment-react/src/pages/404.tsx
import { useNavigate } from 'react-router-dom'
import { Result, Button } from 'antd'

export default function NotFound() {
  const navigate = useNavigate()

  return (
    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
      <Result
        status='404'
        title='404'
        subTitle='页面不存在'
        extra={
          <Button type='primary' onClick={() => navigate('/')}>
            返回首页
          </Button>
        }
      />
    </div>
  )
}
